name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Wasm Pack
      run: cargo install wasm-pack
    - name: Add target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: wasm-pack build
    - name: Upload artifacts
      uses: actions/upload-artifacts@v4
      with:
        name: artifacts
        path: pkg/
